package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"product-reviews/internal/generated"
	"product-reviews/internal/review/models"
)

// Author is the resolver for the author field.
func (r *reviewResolver) Author(ctx context.Context, obj *models.Review) (*generated.User, error) {
	return &generated.User{ID: obj.UserID}, nil
}

// Product is the resolver for the product field.
func (r *reviewResolver) Product(ctx context.Context, obj *models.Review) (*generated.Product, error) {
	return &generated.Product{ID: obj.ProductID}, nil
}

// Review returns generated.ReviewResolver implementation.
func (r *Resolver) Review() generated.ReviewResolver { return &reviewResolver{r} }

type reviewResolver struct{ *Resolver }
